"""ensure email_tokens table exists

Revision ID: 4f9c98227fbb
Revises: d290db6f6dd1
Create Date: 2025-10-21 17:04:36.276767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f9c98227fbb'
down_revision: Union[str, Sequence[str], None] = 'd290db6f6dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_tokens_token'), 'email_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_tokens_token'), table_name='email_tokens')
    op.drop_table('email_tokens')
    # ### end Alembic commands ###
